[package]
name = "bengine"
version = "0.1.0"
edition = "2024"

[profile.release]
#debug = true
lto = true
#strip = false

[features]
colemak = []

[dependencies]
colored = "3.0.0"
log = "0.4.22"
num-traits = "0.2.19"
genawaiter = "0.99.1"
replace_with = "0.1.7"
itertools = "0.14.0"
rapier3d = "0.24.0"
nalgebra = "0.33.2"

[dependencies.ultraviolet]
version = "0.9.2"

[dependencies.obj-rs]
version = "0.7.4"
default-features = false

[dependencies.env_logger]
version = "0.11.5"
default-features = false
features = ["auto-color"]

[dependencies.image]
version = "0.25.2"
default-features = false
features = ["png", "jpeg"]

[dependencies.ash]
version = "0.38.0"
default-features = false
features = ["linked", "debug", "std"]

[dependencies.sdl3]
version = "0.14.27"
default-features = false
features = ["raw-window-handle", "build-from-source-static"]

[build-dependencies]
anyhow = "1.0.89"
colored = "3.0.0"
