[package]
name = "space-game"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
env_logger = "0.11.5"
log = "0.4.22"

[dependencies.image]
version = "0.25.2"
default-features = false
features = ["png"]

[dependencies.ash]
version = "0.38.0"
features = ["linked"]

[dependencies.sdl2]
version = "0.37.0"
features = ["raw-window-handle"]
